### Problem 1
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [5]:
import numpy as np

#### Your code here
np.arange(11.0)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [2]:
#### Your code here
np.linspace(0, 23, 7)

array([  0.        ,   3.83333333,   7.66666667,  11.5       ,
        15.33333333,  19.16666667,  23.        ])

(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [3]:
#### Your code here
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [20]:
#### Your code here

q4 = np.zeros([5, 5], dtype=np.int)
q4 + np.arange(5)
# >>>>>> another solution.
np.tile(np.arange(5), (5,1)).reshape([5, 5])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [8]:
#### Your code here

def isMagic(x):
    '''
    x: check whether x is a magic matrix
    '''
    ## square?
    m = x.shape[0]
    n = x.shape[1]
    if m != n:
        return False
    ## constructed by (1, 2, 3, ... n^2)?
    x2 = x.reshape(m*n)

    if set(x2) != set(np.arange(1, m*n + 1)):
        return False
    ## sums
    colSum = np.sum(x, 0)
    rowSum = np.sum(x, 1)
    diagSum = np.sum(np.diag(x))
    diagSum2 = np.sum(np.diag(x[:, ::-1]))
    if all(colSum == diagSum) and all(rowSum == diagSum) and diagSum == diagSum2:
        return True
    else:
        return False

Here are some tests:

In [10]:
test1 = np.array([[0, 1], 
                  [1, 0]])
isMagic(test1) # False

False

In [29]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

True

In [42]:
test3 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test3) # True

True

In [43]:
test4 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test4) # True

True

In [44]:
test5 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test5) # True

True

### Problem 2

According to this picture, does the "Petal Length" of different species has significant difference? Using the **Analysis of Variance** varify your answer.

![iris](http://slides.nycdatascience.com/BOOTCAMP3/content/week6/pic/scatter.png)

In [12]:
import pandas as pd
from scipy import stats
from sklearn import datasets
raw_data = datasets.load_iris()

Species = raw_data['target_names'][raw_data['target']]
PetalLength = raw_data.data[:,2]
PetalWidth = raw_data.data[:,3]

In [16]:
#### Your code here
index1 = Species == 'setosa'
index2 = Species == 'versicolor'
index3 = Species == 'virginica'
stats.f_oneway(PetalLength[index1], PetalLength[index2], PetalLength[index3])

F_onewayResult(statistic=1179.0343277002194, pvalue=3.0519758018278374e-91)

### Problem 3


We discuss random sampling in the class, which helps when exact solution is hard to obtain. For example, we know that the area of a circle is $\pi \times r^2 \text{, where } r \text{ is the radius of the circle. }$ But we don't know how to approximate the number $\pi$.

Monte Carlo simulation can help.

<img src=monte_carlo.png width=330/>

- Use `np.random.uniform` function to generate 2000 two dimensional samples. `uniform` indicates that the likelihood for any number from **-1 to 1** occurs is uniform. The shape of your sample should look like below (of course the actual numbers can be different)
```
array([[-0.53277773, -0.93122476],
        [ 0.16017788, -0.74177143],
        [ 0.37248292,  0.36734988],
        ..., 
        [ 0.5314644 , -0.50411338],
        [ 0.12208452,  0.6242463 ],
        [ 0.74767075, -0.56486567]])
```
Therefore all the samples fall in the $[-1, 1] \times [-1, 1] \text{ box.}$

In [1]:
import numpy as np
#### Your code here
np.random.seed(18)
pts = np.random.uniform(-1, 1, [2000, 2])

- The probability of points being in the circle is the ratio between the area of the circle and the area of the $[-1, 1] \times [-1, 1] \text{ box.}$ More precisely,

$$\text{Probability} \big( \text{points falling in the circle} \big) = \frac{\text{area of the circle}}{\text{area of the rectangle}} = \frac{\pi}{4},$$

From the sample you generate in the last problem, estimate the probability of falling in the circle, then approximate $\pi$.

In [2]:
#### Your code here
probability = np.mean(pts[:,0]**2 + pts[:,1]**2 <=1)
probability*4 

3.1699999999999999