### Problem 1
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [2]:
import numpy as np

#### Your code here  


In [3]:
np.arange(11.)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [4]:
np.linspace(0,23,7)

array([  0.        ,   3.83333333,   7.66666667,  11.5       ,
        15.33333333,  19.16666667,  23.        ])

In [2]:
#### Your code here

array([  0.        ,   3.83333333,   7.66666667,  11.5       ,
        15.33333333,  19.16666667,  23.        ])

(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [6]:
my_array = np.arange(9)

In [7]:
my_array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#### Your code here

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [9]:
my_liste = list(range(5))*5
print(my_liste)

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [13]:
mat1 = np.array(my_liste).reshape(5,5)
print(mat1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [78]:
def isMagic(a):
    magic_number = sum(a[0,:])
    n = a.shape[0]
    if n!=a.shape[1]:
        return False
    for i in range(a.shape[0]):
        if (sum(a[i,:])!=magic_number) or (sum(a[:,i])!=magic_number):
            return False
    if (sum(np.diag(a))!=magic_number) or (sum(np.diag(np.fliplr(a)))!=magic_number):
            return False
    test = np.arange(1, n*n+1)
    b = a.copy()
    b.shape=(1, n*n)
    b.sort()
    #print(b)
    #print(test)
    if not((b==test).all()):
        return False
    return True

In [79]:
sum(mat1[0,:])

2050

In [80]:
mat1.shape = [1, 25]
print(mat1)
mat1.sort()
print(mat1)

[[   0    0    0 1000    1    1    1    1    1    2    2    2    2    2
     3    3    3    3    3    4    4    4    4    4 1000]]
[[   0    0    0    1    1    1    1    1    2    2    2    2    2    3
     3    3    3    3    4    4    4    4    4 1000 1000]]


In [81]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
b = np.copy(mat1)
print(b)
mat1[0,3]=1000
print(mat1, b)

[[   0    0    0    1    1    1    1    1    2    2    2    2    2    3
     3    3    3    3    4    4    4    4    4 1000 1000]]
[[   0    0    0 1000    1    1    1    1    2    2    2    2    2    3
     3    3    3    3    4    4    4    4    4 1000 1000]] [[   0    0    0    1    1    1    1    1    2    2    2    2    2    3
     3    3    3    3    4    4    4    4    4 1000 1000]]


In [83]:
print(mat1.diagonal(0), mat1.diagonal(1))

[0] [0]


In [84]:
help(np.fliplr)

Help on function fliplr in module numpy.lib.twodim_base:

fliplr(m)
    Flip array in the left/right direction.
    
    Flip the entries in each row in the left/right direction.
    Columns are preserved, but appear in a different order than before.
    
    Parameters
    ----------
    m : array_like
        Input array, must be at least 2-D.
    
    Returns
    -------
    f : ndarray
        A view of `m` with the columns reversed.  Since a view
        is returned, this operation is :math:`\mathcal O(1)`.
    
    See Also
    --------
    flipud : Flip array in the up/down direction.
    rot90 : Rotate array counterclockwise.
    
    Notes
    -----
    Equivalent to m[:,::-1]. Requires the array to be at least 2-D.
    
    Examples
    --------
    >>> A = np.diag([1.,2.,3.])
    >>> A
    array([[ 1.,  0.,  0.],
           [ 0.,  2.,  0.],
           [ 0.,  0.,  3.]])
    >>> np.fliplr(A)
    array([[ 0.,  0.,  1.],
           [ 0.,  2.,  0.],
           [ 3.,  0.,  0.]])
 

In [85]:
#### Your code here  

Here are some tests:

In [86]:
test1 = np.array([[0, 1], 
                  [1, 0]])
isMagic(test1) # False

False

In [87]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

True

In [88]:
test3 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test3) # True

True

In [89]:
test4 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test4) # True

True

In [90]:
test5 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test5) # True

True

### Problem 2

According to this picture, does the "Petal Length" of different species has significant difference? Using the **Analysis of Variance** varify your answer.

![iris](http://slides.nycdatascience.com/BOOTCAMP3/content/week6/pic/scatter.png)

In [92]:
import pandas as pd
from scipy import stats
from sklearn import datasets
raw_data = datasets.load_iris()

Species = raw_data['target_names'][raw_data['target']]
PetalLength = raw_data.data[:,2]
PetalWidth = raw_data.data[:,3]

In [99]:
np.shape(raw_data.data)

(150, 4)

In [100]:
stats.f_oneway(raw_data.data[:50,2], raw_data.data[50:100,2], raw_data.data[100:150,2])

F_onewayResult(statistic=1179.0343277002194, pvalue=3.0519758018278374e-91)

In [16]:
#### Your code here

F_onewayResult(statistic=1179.0343277002194, pvalue=3.0519758018278374e-91)

### Problem 3


We discuss random sampling in the class, which helps when exact solution is hard to obtain. For example, we know that the area of a circle is $\pi \times r^2 \text{, where } r \text{ is the radius of the circle. }$ But we don't know how to approximate the number $\pi$.

Monte Carlo simulation can help.

<img src=monte_carlo.png width=330/>

- Use `np.random.uniform` function to generate 2000 two dimensional samples. `uniform` indicates that the likelihood for any number from **-1 to 1** occurs is uniform. The shape of your sample should look like below (of course the actual numbers can be different)
```
array([[-0.53277773, -0.93122476],
        [ 0.16017788, -0.74177143],
        [ 0.37248292,  0.36734988],
        ..., 
        [ 0.5314644 , -0.50411338],
        [ 0.12208452,  0.6242463 ],
        [ 0.74767075, -0.56486567]])
```
Therefore all the samples fall in the $[-1, 1] \times [-1, 1] \text{ box.}$

In [106]:
sample = np.random.uniform(-1,1, 2)
print(sample, type(sample))
sample2 = np.array([np.random.uniform(-1,1, 2) for _ in range (2000)])
print(sample2)

[-0.05591028  0.4934067 ] <class 'numpy.ndarray'>
[[ 0.34463997  0.48207609]
 [ 0.95255993 -0.86572931]
 [-0.44548274 -0.71662836]
 ..., 
 [ 0.81764076  0.27755825]
 [-0.15337244  0.75864531]
 [ 0.51893592 -0.69108991]]


In [101]:
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than high.  The default value is 1.0.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        

In [22]:
import numpy as np
#### Your code here

- The probability of points being in the circle is the ratio between the area of the circle and the area of the $[-1, 1] \times [-1, 1] \text{ box.}$ More precisely,

$$\text{Probability} \big( \text{points falling in the circle} \big) = \frac{\text{area of the circle}}{\text{area of the rectangle}} = \frac{\pi}{4},$$

From the sample you generate in the last problem, estimate the probability of falling in the circle, then approximate $\pi$.

In [111]:
accu=0 
for i in range(2000):
    if (pow(sample2[i,0], 2)+pow(sample2[i,1],2))<1:  #in circle (distance to center)
        accu+=1
print((accu/2000)*4)   #Pi approximation

3.174


In [113]:
import math
math.pi

3.141592653589793

In [23]:
#### Your code here

3.1699999999999999